import os
from dotenv import load_dotenv

load_dotenv()

NAME_CRAWLER = 'AS-Academy-Shop'

URL_BASE = 'https://as-academy-shop.vercel.app/'

USERNAME = os.getenv('APP_USERNAME')

PASSWORD = os.getenv('APP_PASSWORD')

nombres = [
    "Juan García",
    "María Fernández",
    "Carlos Rodríguez",
    "Laura Martínez",
    "Miguel López",
    "Ana González",
    "Diego Pérez",
    "Sofía Sánchez",
    "Pablo Romero",
    "Lucía Torres",
    "Javier Díaz",
    "Valentina Ruiz",
    "Fernando Herrera",
    "Camila Navarro",
    "Andrés Moreno",
    "Martina Castro",
    "Santiago Ortiz",
    "Carolina Silva",
    "Gabriel Vega",
    "Julieta Molina",
    "Nicolás Ramos",
    "Paula Suárez",
    "Sebastián Medina",
    "Daniela Acosta",
    "Matías Benítez",
    "Florencia Cabrera",
    "Facundo Arias",
    "Agustina Peralta",
    "Tomás Giménez",
    "Victoria Correa",
    "Emiliano Rojas",
    "Catalina Méndez",
    "Lucas Ferreyra",
    "Micaela Ponce",
    "Maximiliano Vargas",
    "Rocío Domínguez",
    "Gonzalo Sosa",
    "Mariana Ibarra",
    "Federico Bustos",
    "Antonella Figueroa",
    "Rodrigo Luna",
    "Constanza Núñez",
    "Leandro Miranda",
    "Florencia Vera",
    "Mauricio Campos",
    "Belén Duarte",
    "Ramiro Suárez",
    "Natalia Molina",
    "Agustín Pereyra",
    "Cecilia Acuña",
    "Iván Márquez",
    "Gabriela Toledo",
    "Franco Vázquez",
    "Elena Giménez",
    "Martín Salazar",
    "Verónica Prieto",
    "Bruno Córdoba",
    "Patricia Alvarado",
    "Hernán Godoy",
    "Silvina Quiroga",
    "Cristian Maldonado",
    "Romina Villalba",
    "Alejandro Escobar",
    "Carla Fuentes",
    "Ignacio Miranda",
    "Noelia Rivas",
    "Ezequiel Correa",
    "Marina Lozano",
    "Germán Núñez",
    "Daniela Vargas",
    "Marcos Paredes",
    "Pilar Santana",
    "Enrique Molina",
    "Claudia Bravo",
    "Joaquín Méndez",
    "Irene Castillo",
    "Hugo Fernández",
    "Beatriz Navarro",
    "Ramón Cabrera",
    "Alicia Romero",
    "Esteban Torres",
    "Lorena Díaz",
    "Raúl Herrera",
    "Mercedes Silva",
    "Alberto Rojas",
    "Susana Vega",
    "Oscar Medina",
    "Teresa Acosta",
    "Manuel Peralta",
    "Silvia Ramos",
    "José Benítez",
    "Cristina Arias",
    "Luis Domínguez",
    "Eva Ponce",
    "Pedro Figueroa",
    "Rosa Méndez",
    "Ángel Bustos",
    "Nuria Campos",
    "Víctor Salazar",
    "Inés Quiroga"
]